apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    team: product
    version: 1.4.0
    environtment: development
  annotations:
    description: ini aplikasi untuk tim produk
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /health
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3
