apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    team: finance
    version: 1.4.5
    environtment: production
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80